### PR TITLE
feat(ci/cd): add release action and version check scripts

### PR DESCRIPTION
**Pull request by Minecrafter-Pythoner**
### Checklist

- [x] Changes have been tested locally and work as expected.
- [x] All tests in workflows pass successfully.
- [x] Documentation has been updated if necessary.
- [x] Code formatting and commit messages align with the project's conventions.
- [x] Comments have been added for any complex logic or functionality if possible.

### This PR is a ..

- [x] 🆕 New feature
- [ ] 🐞 Bug fix
- [ ] 🛠 Refactoring
- [ ] ⚡️ Performance improvement
- [ ] 🌐 Internationalization
- [ ] 📄 Documentation improvement
- [ ] 🎨 Code style optimization
- [ ] ❓ Other (Please specify below)

### Related Issues
None

### Description

Added two scripts under scripts/
* check-version.js is used to verify whether all three version number occurrences (package.json, tauri.conf.json and Cargo.toml) match;
    * usage: `npm run check-version`
* bump-version.js is used to set all version numbers in the mentioned files to a set value.
    * usage: `npm run bump-version 0.0.2`

Added a release.yml workflow under .github/workflows/
* Automatic check, lint, build and create release draft on tag "v*" push (e.g. v0.0.1)
* Checks version number occurrences in all three files and git tag
* Portable exe for Windows x86_64
* Compressed and gzipped app for MacOS aarch64 and x86_64
* Compressed and gzipped executable and AppImage (deb and rpm may not work) for Linux x86_64

### CODE REVIEW

**Comment by UNIkeEN** [comment]
`Build-and-Release.matrix.include.extension` 里的后缀名是？

**Comment by pangbo13** [comment]
有几个建议：
1. release的时候没必要执行linting，每次提交都已经检查了，而且linting也不影响编译
2. 上传没必要单独写一个job，和编译放在一起就行
3. tauri官方的action有上传release的功能，可以直接调用 https://github.com/tauri-apps/tauri-action

**Comment by UNIkeEN** [comment]
* 关于第一、第二点建议表示赞同
* 关于第三点，不使用 tauri-actions 是为了自定义文件名称、提取并上传 portable exec（windows下），这样的情况下还可以部分使用 tauri-actions 吗

**Comment by Minecrafter-Pythoner** [comment]
1. 合理，已修改；
2. 目前的考虑是如果由于某些原因，部分平台编译失败（例如macOS部分编译失败等），它依旧会产生一个含有成功部分artifacts的release draft；在最坏情况下，由于在upload前需要创建release，如果所有平台全部都编译失败，它依旧会创建一个空的release draft。
3. 目前的产物命名需要包含OS名称（macOS 的 app 和 Linux 的 portable exec 均使用 .tar.gz方式打包，需要区分），而 tauri-actions 的产物命名中并不包含OS且未支持自定义命名（见 https://github.com/tauri-apps/tauri-action/issues/571 ）；此外，tauri-actions 也未支持发布Windows 的 portable exe 和 Linux 的 portable exec （见 https://github.com/tauri-apps/tauri-action/issues/302 ）

**Pull request merged**
